package:
  name: scimulator
  version: "0.1.0dev"

source:
  git_rev: v0.1.0dev
  git_url: https://github.com/mfansler/scimulator.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

test:
  imports:
    - scimulator

about:
  home: https://github.com/mfansler/scimulator
  license: BSD
  license_file: LICENSE
