package:
  name: scimulator
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/mfansler/scimulator.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - scimulator

about:
  home: https://github.com/mfansler/scimulator
  license: BSD
  license_file: LICENSE
